name: Check for broken links

on:
  workflow_dispatch:
#  push:
#    branches:
#      - "more-updates"
#  pull_request:
#    paths:
#      - "source/**"

jobs:
  check_links:
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/tech-docs-github-pages-publisher:v4.0.0
    steps:
    - uses: actions/checkout@v3
    - name: htmlproofer
      run: /scripts/check-url-links.sh
