name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

permissions: {}

# Allow one concurrent deployment
concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/tech-docs-github-pages-publisher:v4.0.0
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Compile Markdown to HTML and create artifact
      run: /usr/local/bin/package
    - name: Upload artifact to be published
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        name: github-pages
        path: artifact.tar
        retention-days: 1
        overwrite: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.configure_pages.outputs.base_url }}
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
    - name: Configure Pages
      id: configure_pages
      uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d # v4.0.0
    - name: Deploy to GitHub Pages
      id: deploy_pages
      uses: actions/deploy-pages@decdde0ac072f6dcbe43649d82d9c635fff5b4e4 # v4.0.4

# NOTE: there are just too many, so disabling this job for now.
#
#  url-check:
#    needs: deploy
#    runs-on: ubuntu-latest
#    steps:
#    - name: Download a Build Artifact from build
#      uses: actions/download-artifact@v3
#      with:
#        name: github-pages
#        path: github-pages
#    - name: Unpack files and check URL links
#      run: |
#        cd github-pages
#        tar -xvf artifact.tar
#        npm install linkinator
#        npx linkinator . --recurse --markdown --skip '\-deploy$'
